version: '3.8'

services:
  api:
    image: dmnihal/url-shortener-api:latest
    ports:
      - "8000:8000"
    networks:
      - url-shortener-network
    depends_on:
      - db
      - redis
      - analytics
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/urlshortener
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - api_logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped

  frontend:
    image: dmnihal/url-shortener-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - nginx_logs:/var/log/nginx
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    networks:
      - url-shortener-network
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=urlshortener
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    ports:
      - "5432:5432"
    networks:
      - url-shortener-network
    restart: unless-stopped

  analytics-db:
    image: postgres:14-alpine
    volumes:
      - analytics_data:/var/lib/postgresql/data
      - analytics_db_logs:/var/log/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=analytics
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    ports:
      - "5433:5432"
    networks:
      - url-shortener-network
    restart: unless-stopped

  analytics:
    image: dmnihal/url-shortener-analytics:latest
    ports:
      - "8001:8001"
    networks:
      - url-shortener-network
    depends_on:
      - analytics-db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@analytics-db:5432/analytics
    volumes:
      - analytics_logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    restart: unless-stopped

  worker:
    image: dmnihal/url-shortener-worker:latest
    networks:
      - url-shortener-network
    depends_on:
      - api
      - db
      - redis
    environment:
      - API_URL=http://api:8000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/urlshortener
      - REDIS_URL=redis://redis:6379/0
      - URL_EXPIRY_DAYS=30
    volumes:
      - worker_logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - redis_logs:/var/log/redis
    command: redis-server --appendonly yes
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    networks:
      - url-shortener-network
    restart: unless-stopped

networks:
  url-shortener-network:
    driver: bridge

volumes:
  postgres_data:
  analytics_data:
  redis_data:
  api_logs:
  nginx_logs:
  postgres_logs:
  analytics_db_logs:
  analytics_logs:
  worker_logs:
  redis_logs: 